parameters:
    theodo_scrum_or_not_scrum.manager.user.class: Theodo\Bundle\ScrumOrNotScrumBundle\Manager\UserManager

services:
    theodo_scrum_or_not_scrum.manager.user:
        class: %theodo_scrum_or_not_scrum.manager.user.class%
        arguments: ["@snc_redis.default"]
