parameters:
#    theodo_scrum_or_not_scrum.example.class: Theodo\Bundle\ScrumOrNotScrumBundle\Example

services:
#    theodo_scrum_or_not_scrum.example:
#        class: %theodo_scrum_or_not_scrum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
